---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  METALLB_ADDR_RANGE: 192.168.3.50-192.168.3.199
  VPN_PORT: "51820"
  VPN_GATEWAY_VPN_PORT: "51820"
  VPN_FORWARDED_PORT_1: "59494"
  VPN_COUNTRY: CA
  NETWORK_K8S_CLUSTER_CIDR: "10.42.0.0/16"
  NETWORK_K8S_SERVICE_CIDR: "10.43.0.0/16"
  NETWORK_MANAGEMENT_CIDR: "192.168.0.0/16"
  NETWORK_SERVER_CIDR: "192.168.0.0/16"
  NETWORK_GUEST_CIDR: "192.168.0.0/16"
  GATEWAY_ADDR: 192.168.1.1
  SVC_PIHOLE_ADDR: "192.168.3.80"
  SVC_BLOCKY_ADDR: "192.168.3.88"
  SVC_MARIADB_ADDR: "192.168.3.89"
  SVC_VAULT_ADDR: "192.168.3.90"
  SVC_CONSUL_ADDR: "192.168.3.91"
  SVC_MOSQUITTO_ADDR: "192.168.3.92"
  SVC_HASS_ADDR: "192.168.3.93"
  SVC_LOKI_ADDR: "192.168.3.94"
  VALHEIM_SVC_IP2: "192.168.3.95"
  MC_SURV_ADDR: "192.168.3.96"
  VALHEIM_SVC_IP: "192.168.3.97"
  SVC_SYSLOG_ADDR: "192.168.3.98"
  PLEX_LB: "192.168.3.99"
  NAS1_ADDR: 192.168.1.177
  NAS2_ADDR: 192.168.1.200
  NAS3_ADDR: 192.168.1.207
  NFS_BACKUP: "nfs://192.168.1.200:/volume1/Kubernetes"
