---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - airflow-charts.yaml
  - argo-charts.yaml
  - authentik-charts.yaml
  - bitnami-charts.yaml
  - external-dns.yaml
  - grafana-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-dashboard.yaml
  - longhorn-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minecraft-server-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - nginx-charts.yaml
  - pihole.yaml
  - hashicorp-charts.yaml
  - jenkins-charts.yaml
  - prometheus-community-charts.yaml
  - rocketchat-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - tekton-charts.yaml
  - weaveworks-kured.yaml
  - authelia-charts.yaml
  - onedev-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - kubernetes-sigs-metrics-server-charts.yaml
